package towerwarspp.board;

public enum ChangeArt {
	MOVE_ADDED,
	MOVE_REMOVED,
	ALL_MOVES_REMOVED,
	RANGE_INC,
	RANGE_DEC,
	ENTITY_ADDED,
	ENTITY_REMOVED,
	POSITION_CHANGED,
	ELEMENT_REPLACED,
	HEIGHT_INCREASED,
	HEIGHT_DECREASED,
	TOWER_BLOCKED,
	TOWER_UNBLOCKED
}
